package com.adonis.costAnalyzer.ui.persons;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.*;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class PersonDesign extends HorizontalLayout {
    protected String pictureUploadName;
    protected Image pictureImage;
    protected TextField picture;
    protected Button upload;
    protected TextField firstName;
    protected TextField lastName;
    protected TextField email;
    protected DateField dayOfBirth;
    protected TextField login;
    protected PasswordField password;
    protected TextArea notes;
    protected HorizontalLayout buttonGroup;
    protected Button save;
    protected Button add;
    protected Button delete;
    protected Button cancel;

    public PersonDesign() {
        Design.read(this);
    }
}
